makecode:
  target: microbit
  platform: microbit
  home_url: https://makecode.microbit.org/
theme: jekyll-theme-slate
include:
  - assets
  - variables.md
repository: bibarzgoogle/microbit-tutorials
